// Given two strings s and t which consist of only lowercase letters.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Find the letter that was added in t.

// Example:

// Input:
// s = "abcd"
// t = "abcde"

// Output:
// e

// Explanation:
// 'e' is the letter that was added.


// 1) 位操作：异或
/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
  let len = t.length
  let c = t.charCodeAt(len - 1)
  for (let i = 0; i < len - 1; i++) {
    c ^= s.charCodeAt(i)
    c ^= t.charCodeAt(i)
  }
  return String.fromCharCode(c)
}
// Runtime: 56 ms, faster than 87.79% of JavaScript online submissions for Find the Difference.
// Memory Usage: 35 MB, less than 100.00% of JavaScript online submissions for Find the Difference.